version: "3.8"
services:
  mysqldb:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=test
    ports:
      - 127.0.0.1:3306:3306
  app:
    depends_on:
      - mysqldb
    build: ./app
    ports:
      - 8080:8080
    stdin_open: true
    tty: true
